{"name":"FabricMonitoring_TenanSettings_Settings","ppdf:dataflowId":"0b44ae35-0f90-404f-ab72-1a4c830c1772","ppdf:owner":{"tenantId":"f62b8f20-f16e-4a6e-9b1f-6e2d2e6ac089","userId":"35ccf0d4-9e71-4d15-bebb-7c78661c64b3"},"ppdf:fastCopy":false,"version":"1.0","culture":"en-US","modifiedTime":"2024-02-22T09:21:56.9803494+00:00","ppdf:outputFileFormat":"Parquet","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"fabricmonitoring_tenantsettings_settingCategory":{"queryId":"5690ba08-f7f3-4cb9-b68a-3a8eb2bc0fed","queryName":"fabricmonitoring_tenantsettings_settingCategory","loadEnabled":true},"fabricmonitoring_tenantsettings_settingCategory_DataDestination":{"queryId":"81acf7d4-c712-4055-94e6-afcf7942e5f5","queryName":"fabricmonitoring_tenantsettings_settingCategory_DataDestination"},"fabricmonitoring_tenantsettings_settingCategory_WriteToDataDestination":{"queryId":"158d7582-4e3e-4331-9136-5411563488c6","queryName":"fabricmonitoring_tenantsettings_settingCategory_WriteToDataDestination"},"fabricmonitoring_tenantsettings_settingCategory_TransformForWriteToDataDestinati":{"queryId":"bb57502b-13cc-4994-9906-16b9cf9eec9f","queryName":"fabricmonitoring_tenantsettings_settingCategory_TransformForWriteToDataDestinati"}},"document":"section Section1;\r\n[Staging = \"DefaultStaging\"]\r\nshared fabricmonitoring_tenantsettings_settingCategory = let\r\n  Source = SharePoint.Files(\"https://tommartens.sharepoint.com/sites/PowerBIandSharePoint/\", [ApiVersion = 15]),\r\n  #\"Filtered rows\" = Table.SelectRows(Source, each [Name] = \"tomsSettingCategories.xlsx\"),\r\n  #\"Added custom\" = Table.AddColumn(#\"Filtered rows\", \"ExcelWorkbookContent\", each Excel.Workbook([Content])),\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Added custom\", {\"ExcelWorkbookContent\"}),\r\n  #\"Expanded ExcelWorkbookContent\" = Table.ExpandTableColumn(#\"Removed other columns\", \"ExcelWorkbookContent\", {\"Name\", \"Data\", \"Item\", \"Kind\", \"Hidden\"}, {\"Name\", \"Data\", \"Item\", \"Kind\", \"Hidden\"}),\r\n  #\"Removed other columns 1\" = Table.SelectColumns(#\"Expanded ExcelWorkbookContent\", {\"Data\"}),\r\n  #\"Expanded Data\" = Table.ExpandTableColumn(#\"Removed other columns 1\", \"Data\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\"}, {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\"}),\r\n  #\"Promoted headers\" = Table.PromoteHeaders(#\"Expanded Data\", [PromoteAllScalars = true]),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Promoted headers\", {{\"settingName\", type text}, {\"title\", type text}, {\"tenantSettingGroup\", type text}, {\"Data Residency\", type text}, {\"Data Exfiltration\", type text}, {\"Data Literacy\", type text}, {\"Data security\", type text}, {\"Data Privacy\", type text}, {\"Data Integrity\", type text}, {\"Resource consumption\", type text}})\r\nin\r\n  #\"Changed column type\";\r\nshared DefaultStaging = let\r\n  DefaultStaging = Pipeline.DefaultModelStorage()\r\nin\r\n  DefaultStaging;\r\nshared fabricmonitoring_tenantsettings_settingCategory_DataDestination = let\r\n  Pattern = Lakehouse.Contents([]),\r\n  Navigation_1 = Pattern{[workspaceId = \"cfb8ee98-7eb5-4745-addd-f21dda0bfccb\"]}[Data],\r\n  Navigation_2 = Navigation_1{[lakehouseId = \"06547c78-0a41-41e7-8864-4df81686ac2b\"]}[Data],\r\n  TableNavigation = Navigation_2{[Id = \"fabricmonitoring_tenantsettings_settings_silver\", ItemKind = \"Table\"]}?[Data]?,\r\n  Table = NavigationTable.CreateTableOnDemand(TableNavigation, #table(type table[settingName = nullable text, title = nullable text, tenantSettingGroup = nullable text, Data_Residency = nullable text, Data_Exfiltration = nullable text, Data_Literacy = nullable text, Data_security = nullable text, Data_Privacy = nullable text, Data_Integrity = nullable text, Resource_consumption = nullable text], {}), [DeleteWhenEmpty = true])\r\nin\r\n  Table;\r\n[Staging = \"DefaultStaging\"]\r\nshared fabricmonitoring_tenantsettings_settingCategory_WriteToDataDestination = let\r\n  fabricmonitoring_tenantsettings_settingCategory_WriteToDataDestination = Pipeline.ExecuteAction(ValueAction.WithTransaction([Target = fabricmonitoring_tenantsettings_settingCategory_DataDestination], (txn) => {TableAction.DeleteRows(txn[Target]), () => TableAction.InsertRows(txn[Target], fabricmonitoring_tenantsettings_settingCategory_TransformForWriteToDataDestinati), Action.DoNothing}))\r\nin\r\n  fabricmonitoring_tenantsettings_settingCategory_WriteToDataDestination;\r\nshared fabricmonitoring_tenantsettings_settingCategory_TransformForWriteToDataDestinati = let\r\n    ColumnMappings = {[SourceColumnName = \"settingName\", DestinationColumnName = \"settingName\"], [SourceColumnName = \"title\", DestinationColumnName = \"title\"], [SourceColumnName = \"tenantSettingGroup\", DestinationColumnName = \"tenantSettingGroup\"], [SourceColumnName = \"Data Residency\", DestinationColumnName = \"Data_Residency\"], [SourceColumnName = \"Data Exfiltration\", DestinationColumnName = \"Data_Exfiltration\"], [SourceColumnName = \"Data Literacy\", DestinationColumnName = \"Data_Literacy\"], [SourceColumnName = \"Data security\", DestinationColumnName = \"Data_security\"], [SourceColumnName = \"Data Privacy\", DestinationColumnName = \"Data_Privacy\"], [SourceColumnName = \"Data Integrity\", DestinationColumnName = \"Data_Integrity\"], [SourceColumnName = \"Resource consumption\", DestinationColumnName = \"Resource_consumption\"]},\r\n    SourceColumns = Table.SelectColumns(fabricmonitoring_tenantsettings_settingCategory, List.Transform(ColumnMappings, each _[SourceColumnName])),\r\n    TargetColumns = Table.RenameColumns(SourceColumns, List.Transform(ColumnMappings, each {_[SourceColumnName], _[DestinationColumnName]}))\r\nin\r\n    TargetColumns;\r\n","connectionOverrides":[{"path":"https://tommartens.sharepoint.com/sites/PowerBIandSharePoint/","kind":"SharePoint","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"SharePoint\",\"path\":\"https://tommartens.sharepoint.com/sites/PowerBIandSharePoint/\"}","audience":null},{"path":"Lakehouse","kind":"Lakehouse","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Lakehouse\",\"path\":\"Lakehouse\"}","audience":null}]},"entities":[{"$type":"LocalEntity","name":"fabricmonitoring_tenantsettings_settingCategory","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"fabricmonitoring_tenantsettings_settingCategory.parquet"},"annotations":[{"name":"ppdf:entityKeys","value":"[]"}],"attributes":[{"name":"settingName","dataType":"string"},{"name":"title","dataType":"string"},{"name":"tenantSettingGroup","dataType":"string"},{"name":"Data Residency","dataType":"string"},{"name":"Data Exfiltration","dataType":"string"},{"name":"Data Literacy","dataType":"string"},{"name":"Data security","dataType":"string"},{"name":"Data Privacy","dataType":"string"},{"name":"Data Integrity","dataType":"string"},{"name":"Resource consumption","dataType":"string"}]}]}